from discord.ext import commands


class InvalidModalField(Exception): ...


class GuildOnly(commands.CheckFailure): ...


class StaffOnly(commands.CheckFailure): ...


class GeneralOnly(commands.CheckFailure): ...


class SilentCheckFailure(commands.CheckFailure): ...


class InvalidURL(Exception): ...


class ActivityEventBreak(commands.CheckFailure): ...
